version: '2'
services: 
  main: 
    image: jeepend/ubuntu_jenkins_ftp_supervisor
    ports: 
      - '8080:8080' # jenkins
      - '20-21:20-21' # vsftpd
      - '21100-21110:21100-21110' #vsftpd
      - '9001:9001' # supervisor
    volumes: 
      - '/Users/jeepend/jenkins:/var/lib/jenkins'
      - '/Users/jeepend/docker/ftp:/srv/ftp'
    tty: true
