version: '2'
services: 
  main: 
    image: jeepend/ubuntu_jenkins_ftp_supervisor
    restart: always
    ports: 
      - '8080:8080' # jenkins
      - '20-21:20-21' # vsftpd
      - '21100-21110:21100-21110' #vsftpd
      - '9001:9001' # supervisor
    volumes: 
      - '/home/jeepend/workspace/jenkins:/var/lib/jenkins'
      - '/home/jeepend/workspace/ftp:/srv/ftp'
      - '/etc/localtime:/etc/localtime' # timesone
      - '/etc/timezone:/etc/timezone' # timezone
    tty: true # Allocate a pseudo-TTY (same with docker run -t)
    stdin_open: true # Keep STDIN open even if not attached (same with docker run -i)
