version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.1
    depends_on:
      - nginx
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    links:
      - 'nginx:es'
