version: '2'
services: 
  main: 
    image: jeepend/ubuntu-cv22-vnc
    restart: always
    ports: 
      - '10022:22' # ssh
      - '6080:80' # vnc-http
      - '5900:5900' # vnc
    volumes: 
      - '/etc/localtime:/etc/localtime' # timesone
      - '/etc/timezone:/etc/timezone' # timezone
      - '/dev/shm:/dev/shm'
      - '/home/jeepend/workspace/cv22:/root/cv22'
    tty: true # Allocate a pseudo-TTY (same with docker run -t)
    stdin_open: true # Keep STDIN open even if not attached (same with docker run -i)
    environment:
      RESOLUTION: 1920x1080
